name: Build
on: [push]
jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          registry-url: 'https://registry.npmjs.org'
      - run: git diff --quiet
      - run: npm install
      - run: npm link
      - run: cd $GITHUB_WORKSPACE/examples/dev-expressions && klap build
      - run: cd $GITHUB_WORKSPACE/examples/dynamic-imports && klap build
      - run: cd $GITHUB_WORKSPACE/examples/jsx-runtime && klap build
      - run: cd $GITHUB_WORKSPACE/examples/minimal && klap build
      - run: cd $GITHUB_WORKSPACE/examples/react-component && klap build
      - run: cd $GITHUB_WORKSPACE/examples/react-sc-typescript && klap build
      - run: cd $GITHUB_WORKSPACE/examples/react-typescript && klap build
      - run: cd $GITHUB_WORKSPACE/examples/scaffold && klap build
      - run: cd $GITHUB_WORKSPACE/examples/scaffold-typescript && klap build
      - run: cd $GITHUB_WORKSPACE/examples/typedefs && klap build
      - run: npm run format
      - run: git diff --quiet
      - run: npm run semantic-release
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

