name: Build
on: [push]
jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: npm install
      - run: npm link
      - run: cd $GITHUB_WORKSPACE/examples/dev-expressions && klap build
      - run: cd $GITHUB_WORKSPACE/examples/dynamic-imports && klap build
      - run: cd $GITHUB_WORKSPACE/examples/jsx-runtime && klap build
      - run: cd $GITHUB_WORKSPACE/examples/minimal && klap build
      - run: cd $GITHUB_WORKSPACE/examples/react-component && klap build
      - run: cd $GITHUB_WORKSPACE/examples/react-sc-typescript && klap build
      - run: cd $GITHUB_WORKSPACE/examples/react-typescript && klap build
      - run: cd $GITHUB_WORKSPACE/examples/scaffold && klap build
      - run: cd $GITHUB_WORKSPACE/examples/scaffold-typescript && klap build
      - run: cd $GITHUB_WORKSPACE/examples/typedefs && klap build
      - run: git diff --name-only --quiet

